# Generated by Django 3.0.8 on 2020-07-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_client', models.CharField(max_length=24)),
                ('g_score', models.IntegerField()),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
